metaverso:
  backend_url: https://metaverso.medialab.ufg.br/v1
  username: scanner@example.com
  password: scanner
  waittime: 30

printer:
  default_preset: PLA
  list:
    - name: K1_Max
      ip: 192.168.20.175
      type: slic3r
      websocket_port: 9999

paths:
  models: models
  output: data/output
  slicer_executable: C:\Users\USER\Downloads\Slic3r-1.3.0.64bit\Slic3r-console.exe
  slicer_config: config\slic3r_k1max.ini

logging:
  level: INFO
